language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm-nightly
  
before_script:
  - composer install

script: 
  - bin/phpunit --coverage-text
